# 2.針對所有城市(City)，計算總收入前3高的城市，個別分析其總收入、總費用及總退款的金額等重要特徵。

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

sns.set(style="whitegrid")
pd.set_option('display.max_columns', None)
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)
plt.rcParams['axes.unicode_minus'] = False # 正常顯示負號

In [ ]:
# Colab 進行matplotlib繪圖時顯示繁體中文
# 下載台北思源黑體並命名taipei_sans_tc_beta.ttf，移至指定路徑
!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.font_manager import fontManager

# 改style要在改font之前
# plt.style.use('seaborn')

fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
mpl.rc('font', family='Taipei Sans TC Beta')

# EDA

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/大三/上學期/大數據決策/期末報告/customer_data_handled.csv')

df

# Processing Data

# Revenue, Cost, and Refund

In [ ]:
# Selection Columns & Groupby & Sort_values
df_price = df[['城市' ,'總收入' ,'總費用' ,'總退款']].groupby('城市').sum().reset_index().sort_values(by='總收入' ,ascending=0)
print(df_price.head())

# City Revenue Top3
df_top3 = df_price.head(3)
print(df_top3)           # Los Angeles, San Diego, Sacramento

In [ ]:
plt.figure(figsize=(12, 6))
bar_width = 0.2
bar_positions1 = np.arange(len(df_top3['城市']))
bar_positions2 = bar_positions1 + bar_width
bar_positions3 = bar_positions2 + bar_width

plt.bar(bar_positions1, df_top3['總收入'], width=bar_width, color='orange', label='Total Revenue')
plt.bar(bar_positions2, df_top3['總費用'], width=bar_width, color='blue', label='Total Cost')
plt.bar(bar_positions3, df_top3['總退款'], width=bar_width, color='yellow', label='Total Refund')

plt.title('Top 3 Cities by Total Revenue, Cost, and Refund')
plt.xlabel('City')
plt.ylabel('Amount')
plt.xticks(bar_positions2, df_top3['城市'])
plt.legend()
plt.show()

透過圖表可看出總收入的前三高排名順序分別為Los Angeles、San Diego、Sacramento

總費用的順序也是Los Angeles、San Diego、Sacramento

In [ ]:
# Refund
df_refund = df_top3.sort_values(by='總退款', ascending=False)

plt.figure(figsize=(8, 6))
bar_positions = np.arange(len(df_refund['城市']))

sns.barplot(x=bar_positions, y=df_refund['總退款'], palette="Set3")
plt.title('Top 3 Cities by Total Refund')
plt.xlabel('City')
plt.ylabel('Amount')
plt.xticks(bar_positions, df_refund['城市'])
plt.show()

圖表可看出總退款的順序則是San Diego、Sacramento、Los Angeles

# Number of People in Los Angeles, San Diego, and Sacramento

In [ ]:
# City Selection
selected_cities = ['Los Angeles', 'San Diego', 'Sacramento']

# 各城市的人數
city_data_selected = df[df['城市'].isin(selected_cities)][['客戶編號', '城市']]

city_counts = city_data_selected['城市'].value_counts().reset_index().rename(columns={'index': '城市', '城市': 'city'})
print(city_counts)

plt.figure(figsize=(10, 6))
sns.barplot(x='城市', y='city', data=city_counts, palette='Set3')
plt.title('Number of People in Los Angeles, San Diego, and Sacramento')
plt.xlabel('City')
plt.ylabel('Number of People')
plt.show()

從圖表得知 Los Angeles 人數287最多，San Diego 278第二， Sacramento 107第三

# Gender Distribution in Selected Cities

In [ ]:
# 各城市的男女人數
city_data_selected = df[df['城市'].isin(selected_cities)][['性別', '城市']]

plt.figure(figsize=(12, 6))
sns.countplot(x='城市', hue='性別', data=city_data_selected, palette='Set2')
plt.title('Gender Distribution in Selected Cities')
plt.xlabel('City')
plt.ylabel('Number of People')
plt.legend(title='Gender', loc='upper right')
plt.show()

圖表得知Los Angeles的女性比男性多，其餘城市皆是男性多於女性

# Marital Status Distribution in Selected Cities

In [ ]:
city_data_selected = df[df['城市'].isin(selected_cities)][['婚姻', '城市']]

plt.figure(figsize=(12, 6))
sns.countplot(x='城市', hue='婚姻', data=city_data_selected, palette='Set2')
plt.title('Marital Status Distribution in Selected Cities')
plt.xlabel('City')
plt.ylabel('Number of People')
plt.legend(title='Marital Status', loc='upper right')
plt.show()

三個城市的結婚狀態都是No>Yes，也就是沒結婚人數大於有結婚人數

# Age Distribution in Selected Cities

In [ ]:
# 各城市的年齡分布
city_data_selected = df[df['城市'].isin(selected_cities)][['年齡', '城市']]

plt.figure(figsize=(12, 6))
sns.boxplot(x='城市', y='年齡', data=city_data_selected, palette='Set2')
plt.title('Age Distribution in Selected Cities')
plt.xlabel('City')
plt.ylabel('Age')
plt.show()

San Diego的年齡箱型圖看出，它的四分位間距跟其他兩者相比偏長，代表著San Diego的年齡分布較廣，下四分位數最低，上四分位數跟中位數都是最高

Los Angeles人口最多，但上四分位數最低，下四分位數第二低，平均年齡也是最低，代表著Los Angeles的人口年齡偏年輕